[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.41"

[dependencies.mongodb]
version = "3.2.5"